### ISSUE TITLE
Error in MQ4 sensor calibrating

### ISSUE THREAD

**Issue by Dimitrah** [miguel5612/MQSensorsLib#19]
at examples/MQ-4/MQ-4.ino there is an error in the if function:
//Rutina de calibracion - Uncomment if you need (setup too and header)
  if(calibration_button)
  {
    float R0 = MQ4.calibrate();
    MQ4.setR0(R0);
  }

calibration_button=13 and so the if statement is always true.
Instead of if(calibration_button) should be if(digitalRead(calibration_button==High)).

**Comment by miguel5612** [comment]
Hello Dimitrah.
We are processing your request, in the coming weeks we will be publishing the steps to implement the solution :). We appreciate your patience

**Comment by miguel5612** [comment]
This was fixed on 2.0 version, please update and it will work well.
![image](https://user-images.githubusercontent.com/18131167/77976683-3e70f200-72c3-11ea-96e4-ab4349bb3850.png)

If problem continues, please open a new issue
