### ISSUE TITLE
Support for NodeMCU

### ISSUE THREAD

**Issue by filips123** [miguel5612/MQSensorsLib#21]
Does this library supports NodeMCU? If not, can it be updated to support it?

**Comment by miguel5612** [comment]
Good day flips, we regret the delay, we have carried out the analysis and we have determined that the issues you have raised will be resolved in the following order:
Check compatibility with the digital output.
2. Compatibility with NodeMcu
3. Connection with external A/D converters to a nodemcu.
In the following weeks we will be answering your questions one by one, we appreciate your patience.

**Comment by miguel5612** [comment]
NodeMcu support was added on the release 1.10, please update your library and load your code on the ESP, please take care with voltage managment. Review the readme, any issue contact us :)
![image](https://user-images.githubusercontent.com/18131167/77976565-f6ea6600-72c2-11ea-98e0-b21058a567fb.png)
