### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by Pmsaini89** [miguel5612/MQSensorsLib#25]
How to use it with esp32 board.

**Comment by miguel5612** [comment]
Hi Pmsaini89,
We have deployed a new release to have example on ESP-32 board.
Here is the result on the serial port:
![image](https://user-images.githubusercontent.com/18131167/78454484-d7a25e80-765d-11ea-9f62-10c342b5c5be.png)
And this is the example code:
https://github.com/miguel5612/MQSensorsLib/blob/master/examples/ESP32/esp32.ino
Board used was wemos ESP-32S.

**Comment by Pmsaini89** [comment]
Hi miguel5612, 
 Thank you very much, I appreciate your work.
