### ISSUE TITLE
setRL() Float type error

### ISSUE THREAD

**Issue by pedrorocha014** [miguel5612/MQSensorsLib#37]
Hello how are you ?
I need to set the value of the RL variable to 0.4 ohms, because my MQ7 sensor has a maximum potentiometer resistance equal to this value... 
But every time I set the value to 0.4 he understands it to be 0 ... is this a bug? If not how can I solve this?

![error](https://user-images.githubusercontent.com/48830542/94378225-3cff7580-00fe-11eb-935f-ee1c2c5ff53d.PNG)

**Comment by miguel5612** [comment]
Best regards,
I totally agree, RL internally was stored as Byte type and for this reason the decimal values 0.4 were close to zero, the type has been changed to float and corrected.
