### ISSUE TITLE
Serial outputs table but I only want the ppm result of that table

### ISSUE THREAD

**Issue by quintendewilde** [miguel5612/MQSensorsLib#38]
@miguel5612  I loooooove your library!!!! Only one that works of the bat. 

But I can't seem to find how to get the ppm of an mq4 and mq8 sensor.

**Comment by KlausMu** [comment]
float ppm = MQ4.readSensor();

The method "readSensor()" has a return value. Only the examples are not using it.

**Comment by miguel5612** [comment]
Thanks [KlausMu](https://github.com/KlausMu) Thats correct!
