### ISSUE TITLE
Issues with MQUnifiedsensor  existing with SSD1306

### ISSUE THREAD

**Issue by Sussassin** [miguel5612/MQSensorsLib#47]
**Describe the bug**
When using on Arduino nano, if using MQ135 alone works fine.
When using Adafruit SSD1306 alone this works fine.
When using both together. Unit locks up when calling MQU Library. 
Only happens intermittently. Nano locks up and doesn't respond or display freezes and code stops

**To Reproduce**
4. See code below where sections have been commented out.

**Expected behavior**
Expect both to co-exist

**Additional context**
//Include the library

#include <SPI.h>
#include <Wire.h>
//#include <Adafruit_GFX.h>
//#include <Adafruit_SSD1306.h>
#include <MQUnifiedsensor.h>

//#define SCREEN_WIDTH 128 // OLED display width, in pixels
//#define SCREEN_HEIGHT 64 // OLED display height, in pixels

// Declaration for an SSD1306 display connected to I2C (SDA, SCL pins)
//#define OLED_RESET -1 // Reset pin # (or -1 if sharing Arduino reset pin)
//Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

//Definitions
#define placa "Arduino Nano"
#define Voltage_Resolution 5
#define pin A0 //Analog input 0 of your arduino
#define type "MQ-135" //MQ135
#define ADC_Bit_Resolution 10 // For arduino UNO/MEGA/NANO
#define RatioMQ135CleanAir 3.6//RS / R0 = 3.6 ppm  
#define calibration_button 13 //Pin to calibrate your sensor

//Declare Sensor
MQUnifiedsensor MQ135(placa, Voltage_Resolution, ADC_Bit_Resolution, pin, type);

void setup() {

Serial.begin(115200); //Init serial port

   /************************************** OLED INIT ***********************************/ 
 SSD1306_SWITCHCAPVCC = generate display voltage from 3.3V internally
 if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) { 
   Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }

  // Show initial display buffer contents on the screen --
  // the library initializes this with an Adafruit splash screen.
 display.display();
  delay(2000); // Pause for 2 seconds

  // Clear the buffer
  display.clearDisplay();
 display.display();
  // Draw a single pixel in white
  display.drawPixel(10, 10, WHITE);

  // Show the display buffer on the screen. You MUST call display() after
  // drawing commands to make them visible on screen!
 delay(2000);

 /************************************************************************************/ 
  
  //Init the serial port communication - to debug the library
  

  //Set math model to calculate the PPM concentration and the value of constants
  MQ135.setRegressionMethod(1); //_PPM =  a*ratio^b
  
  /*****************************  MQ Init ********************************************/ 
  //Remarks: Configure the pin of arduino as input.
  /************************************************************************************/ 
  MQ135.init(); 
  /* 
    //If the RL value is different from 10K please assign your RL value with the following method:
    MQ135.setRL(10);
  */
  /*****************************  MQ CAlibration ********************************************/ 
  // Explanation: 
  // In this routine the sensor will measure the resistance of the sensor supposing before was pre-heated
  // and now is on clean air (Calibration conditions), and it will setup R0 value.
  // We recomend execute this routine only on setup or on the laboratory and save on the eeprom of your arduino
  // This routine not need to execute to every restart, you can load your R0 if you know the value
  // Acknowledgements: https://jayconsystems.com/blog/understanding-a-gas-sensor
  Serial.print("Calibrating please wait.");
  float calcR0 = 0;
  for(int i = 1; i<=10; i ++)
  {
    MQ135.update(); // Update data, the arduino will be read the voltage on the analog pin
    calcR0 += MQ135.calibrate(RatioMQ135CleanAir);
    Serial.print(".");
  }
  MQ135.setR0(calcR0/10);
  Serial.println("  done!.");
  
  if(isinf(calcR0)) {Serial.println("Warning: Conection issue founded, R0 is infite (Open circuit detected) please check your wiring and supply"); while(1);}
  if(calcR0 == 0){Serial.println("Warning: Conection issue founded, R0 is zero (Analog pin with short circuit to ground) please check your wiring and supply"); while(1);}
  /*****************************  MQ CAlibration ********************************************/ 
  Serial.println("** Air Quality Sensor from MQ-135 ****");
  //Serial.println("|    CO   |  Alcohol |   CO2  |  Toluene  |  NH4  |  Acetone  |");  
}

void loop() {

//  MQ135.update(); // Update data, the arduino will be read the voltage on the analog pin

//  MQ135.setA(605.18); MQ135.setB(-3.937); // Configurate the ecuation values to get CO concentration
//  float CO = MQ135.readSensor(); // Sensor will read PPM concentration using the model and a and b values setted before or in the setup
//
//  MQ135.setA(77.255); MQ135.setB(-3.18); // Configurate the ecuation values to get Alcohol concentration
//  float Alcohol = MQ135.readSensor(); // Sensor will read PPM concentration using the model and a and b values setted before or in the setup

//  MQ135.setA(110.47); MQ135.setB(-2.862); // Configurate the ecuation values to get CO2 concentration
//  float CO2 = MQ135.readSensor(); // Sensor will read PPM concentration using the model and a and b values setted before or in the setup

//  MQ135.setA(44.947); MQ135.setB(-3.445); // Configurate the ecuation values to get Tolueno concentration
//  float Tolueno = MQ135.readSensor(); // Sensor will read PPM concentration using the model and a and b values setted before or in the setup

//  MQ135.setA(102.2 ); MQ135.setB(-2.473); // Configurate the ecuation values to get NH4 concentration
//  float NH4 = MQ135.readSensor(); // Sensor will read PPM concentration using the model and a and b values setted before or in the setup

//  MQ135.setA(34.668); MQ135.setB(-3.369); // Configurate the ecuation values to get Acetona concentration
//  float Acetona = MQ135.readSensor(); // Sensor will read PPM concentration using the model and a and b values setted before or in the setup
//   Serial.println("|    CO    |  Alcohol |   CO2    |  Toluene |  NH4     |  Acetone |");  
//  Serial.print("|   "); Serial.print(CO); 
//  Serial.print("   |   "); Serial.print(Alcohol); 
//  Serial.print("   |   "); Serial.print(CO2); 
//  Serial.print("   |   "); Serial.print(Tolueno); 
//  Serial.print("   |   "); Serial.print(NH4); 
//  Serial.print("   |   "); Serial.print(Acetona);
//  Serial.println("   |"); 
//  Serial.println(); 
 

//  delay(10000); //Sampling frequency
}

**Comment by miguel5612** [comment]
Best regards,
The problems you indicate have occurred due to the intenro collapse of the timers of the microcontroller inside the arduino, my suggestion in this case is that you base on the example MQ135 ADS1110 to implement the library using an external ADC converter, this way you can in the arduino have only the mathematical operations of reading the sensor and leave the task of reading the voltage to the external ADC converter and thus no longer collapses your program.
