### ISSUE TITLE
How to obtain RL

### ISSUE THREAD

**Issue by larrywal-express** [miguel5612/MQSensorsLib#72]
![IMG_20231028_153549_edit_68616741962417](https://github.com/miguel5612/MQSensorsLib/assets/62125055/3379666c-d5f5-41eb-a90c-b321b2a7ee0a)

Using the image sensor, is there a better way to obtain its RL intead of using the default 10k?

**Comment by razarate** [comment]
You should take the resistance smd code and "convert it". Try google it. Its easy.

**Comment by miguel5612** [comment]
he SMD code on the resistor. This method provides a more accurate resistance value than relying on the default 10k. Please refer to online resources for guidance on converting SMD codes. Thank you for your input.
